---
abstract: 'Create symlinks in one directory for files in another'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  Test::Script: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-LinkDir
no_index:
  directory:
    - t
    - utils
requires:
  File::Path: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=File-LinkDir
  homepage: http://search.cpan.org/dist/File-LinkDir/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/file-linkdir.git
version: 0.06
x_authority: cpan:HINRIK
